### ISSUE TITLE
Disable upload of content types when not allowed

### ISSUE THREAD

**Issue by t-schroeder** [h5p/h5p-editor-php-library#87]
When someone doesn't have the "mod/hvp:updatelibraries" capability wouldn't it make sense to disable upload of own Content types/libraries? As I understand it each Content type is also a library. So if you can't install/update libraries is there even any Content type you can upload? If not I would suggest disabling the upload dialog for .h5p files in that case.

I already mentioned in #86 that the error message you get when missing this capability and trying to upload a new Content type is not great. This issue describes basically the same problem. Namely that it's not clear to the user what he can actually upload in this scenario.

**Comment by otacke** [comment]
@t-schroeder A content file is merely a zip archive that contains all libraries that the content type uses + media content used + the parameters given. Those libraries inside are not installed every time someone uploads content, but only if the libraries in that particular version are not present on the system and the user has the capability to upload libraries.

Not preventing file uploads if someone doesn't have the updatelibraries capabilities makes sense because otherwise users could not restore content that they may have made a backup of and they couldn't share content with others on other platforms. With the rules as they are today, users can do this while they can't install newer library versions that come with newer content type versions.

**Comment by t-schroeder** [comment]
@otacke thanks for clarifying that. I'm closing the issue.
